channels.go, cmd/slackdump/slackdump.go, cmd/slackdump/slackdump_test.go, common.go, go.mod, go.sum, slackdump.go
Wake up in the morning to discover that rate-limit handling logic was FUBAR.
Should fix #1
=> Fix rate limiter and light refactor of the main()

README.rst
Just a few tweaks to spelling, grammar, and phrasing; and added a common use case.
=> Minor updates to phrasing, spelling, grammar

cmd/slackdump/main.go, go.mod, go.sum, internal/app/config.go, internal/app/config_test.go, slackdump.go, slackdump_test.go
=> Add support for cookies.txt

internal/app/config.go, slackdump.go, users.go
- Add tracing
- organize code around verifying slack credentials
=> Additional tracing

.gitignore, examples/python/print_messages.py, examples/sample.json
Add a python example of reading the messages json file.
=> Add a python example

README.rst
Helpful for people who haven't used web browser dev tools before
=> Document how to open developer tools

doc/usage-export.rst
- mention slack export viewer in docs
- this refers to #63
=> mention slack export viewer in docs

internal/export/export.go, internal/export/export_test.go, slackdump.go, slackdump_test.go
Fixes: https://github.com/rusq/slackdump/discussions/77
=> fix -no-user-cache regression

README.rst
=> Documentation for #83

export/message.go
=> remove omitempty for user struct

auth/browser/browser.go
Forgot to save before pushing the last one.  Relates to #133 and #126
=> Add expiry time for cookie consent cookie for EZ Login 3000 session

README.rst, cmd/slackdump/interactive.go, cmd/slackdump/main.go, doc/README.rst, doc/usage-emoji.rst
- add emoji mode to the UI
- doc update
=> Emoji menu and doc update

cmd/slackdump/interactive.go
=> #153: add an export token to the UI

README.rst, doc/login-manual.rst
=> #122: simplify token retrieval steps (thanks @mootari)

export/export.go
=> fix DM attachment directory location

export/index.go
=> initialise channels.json with empty list, if empty

cmd/slackdump/main.go
- If `-auth-reset` is specified and:
- no mode flags are given: reset auth and exit
- mode flags are given: continue execution.
Fixes #177
=> Reset auth even if there's no mode flags

.github/workflows/release.yml, .gitignore, .goreleaser.yaml, Makefile, cmd/slackdump/main.go, cmd/slackdump/version.go
Replace go-release-action with goreleaser (see #173)
=> Goreleaser

.github/workflows/go.yml, contrib/README.md, contrib/_gen/readme.md.tmpl, contrib/_gen/update.go, contrib/catalogue.yaml, contrib/messages_json_parsing/jq/find_matches_print_dates_and_text.sh, contrib/messages_json_parsing/jq/print_messages.sh, contrib/messages_json_parsing/python/print_messages.py
As per discussion: https://github.com/rusq/slackdump/discussions/193
(Thanks Levi)
=> adding an incremental backup script (by @levigroker)

export/export.go, internal/network/limiter.go, internal/network/limiter_test.go, internal/network/network.go, internal/network/network_test.go, slackdump.go
=> merge network package from v3 (fixes #212)

cmd/slackdump/main.go
As per request: https://t.me/slackdump/958
=> add workspace flag

auth/browser.go, auth/browser/browser.go, auth/browser/client.go, auth/browser/extractors.go, auth/option.go, cmd/slackdump/main.go, cmd/slackdump/main_test.go
- handle nil request value
- increase the default login page timeout to 5 min
- remove unneded check
- -browser-timeout parameter
Fixes #240
=> Playwright error handling and increased login timeout (5min)

contrib/incremental_backup/README.txt, contrib/incremental_backup/dump.sh
=> Add the missing dump.sh

Dockerfile
=> Update Dockerfile to use golang 1.21

auth/browser/client.go, auth/browser/client_test.go, cmd/slackdump/main.go, go.mod, go.sum
=> Upgrade playwright and introduce -browser-reinstall flag

auth/browser.go, auth/browser/browser.go, auth/browser/client.go, auth/option.go, cmd/slackdump/main.go
Enabling playwright verbose output.
=> propagate verbose to playwright

cmd/slackdump/interactive.go
PR to collect issues discovered during testing
=> v2.5.0 beta fixes

downloader/downloader.go, go.mod, go.sum
- **fix race condition in downloader**
- **update slackauth to fix cookie capture**
=> v2.5.6 patch

.github/workflows/codeql-analysis.yml, .github/workflows/go.yml, cmd/slackdump/internal/export/v3_test.go, internal/chunk/obfuscate/obfuscate_test.go, internal/chunk/transform/export_test.go, internal/chunk/transform/standard_test.go, internal/convert/chunkexp_test.go, internal/fixtures/fixtures.go, internal/structures/index_test.go, internal/viewer/source/export_test.go
For the time being, some tests that rely on local data will
be skipped when the tests are running in CI.
=> skip some tests in CI

.github/workflows/go.yml, .github/workflows/release.yml, Makefile, auth/auth_test.go, go.mod
- **update test for go 1.23**
- **update build system**
Fixes #318.
=> Fix test for go1.23, and bump go version

README.rst
- **add brew command**
- **formatting test**
- **formatting**
=> Add brew instruction to readme

.gitignore, cmd/slackdump/internal/apiconfig/apiconfig.go, cmd/slackdump/internal/apiconfig/apiconfig_test.go, cmd/slackdump/internal/apiconfig/check.go, cmd/slackdump/internal/apiconfig/new.go, cmd/slackdump/internal/apiconfig/new_test.go, go.mod, go.sum
Switch to TOML instead of YAML for apiconfig
=> Toml apiconfig

auth/auth.go, auth/browser.go, auth/browser/client.go, auth/rod.go, go.mod, go.sum
- **stop spinner if challenge code is requested in headless flow**
- **make playwright init beautiful**
=> Auth spinner

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/go.yml, auth/browser/client_test.go, cmd/slackdump/internal/diag/encrypt_test.go, cmd/slackdump/internal/emoji/emojidl/emoji_test.go, cmd/slackdump/internal/export/v3_test.go, internal/chunk/dirproc/filetracker_test.go, internal/chunk/filemgr_test.go, internal/chunk/transform/export_test.go, internal/chunk/transform/fileproc/sp_dump.go, internal/chunk/transform/fileproc/sp_export.go, internal/chunk/transform/standard_test.go, internal/convert/chunkexp_test.go, internal/fixtures/fixtures.go, internal/osext/compression_test.go, internal/osext/dir_test.go, internal/viewer/source/export_test.go
- add GHA job to build on windows
=> add windows build

.github/workflows/docker.yml, Dockerfile, internal/chunk/filemgr_test.go, internal/edge/edge_test.go, internal/fixtures/fixtures.go
- **Update docker build**
- **Add docker deployment workflow**
=> Dockerhub deployment

README.md
change qickstart to quickstart
=> fix typo in readme README.md

.gitignore, internal/viewer/renderer/fixtures/polly.html, internal/viewer/renderer/fixtures/polly.json, internal/viewer/renderer/slack_action.go, internal/viewer/renderer/slack_fixtures_test.go, internal/viewer/renderer/slack_section.go, internal/viewer/renderer/slack_test.go
- Fix polly messages parsing.
Fixes #406
=> Viewer: polly messages

cmd/slackdump/internal/archive/archive.go, cmd/slackdump/internal/archive/archive_wizard.go, cmd/slackdump/internal/archive/search.go, cmd/slackdump/internal/cfg/cfg.go, cmd/slackdump/internal/convertcmd/convert.go, cmd/slackdump/internal/dump/dump.go, cmd/slackdump/internal/emoji/emoji.go, cmd/slackdump/internal/export/v3.go, cmd/slackdump/internal/export/wizard.go, cmd/slackdump/internal/list/common.go, cmd/slackdump/internal/ui/cfgui/common_params.go, internal/chunk/control/control.go, internal/chunk/control/noop.go, internal/chunk/control/workers.go, internal/chunk/dirproc/users.go, internal/chunk/transform/export.go, internal/chunk/transform/fileproc/avatar.go, internal/chunk/transform/fileproc/avatar_test.go, internal/chunk/transform/fileproc/fileproc.go, internal/chunk/transform/standard.go, internal/convert/chunkexp.go, processor/processor.go, slackdump.1, stream/stream.go, stream/stream_workers.go
- **implement avatar download in export and archive**
- **commit progress**
- **Update converter to support avatars**
=> i268 avatars

cmd/slackdump/internal/convertcmd/convert.go, cmd/slackdump/internal/diag/hydrate.go, cmd/slackdump/internal/diag/hydrate_mock_test.go, cmd/slackdump/internal/diag/hydrate_test.go, cmd/slackdump/internal/diag/redownload.go, cmd/slackdump/internal/export/v3.go, internal/chunk/directory.go, internal/chunk/file.go, internal/chunk/file_test.go, internal/chunk/player.go, internal/chunk/transform/export.go, internal/convert/chunkexp.go, internal/source/chunkdir.go, internal/source/dump.go, internal/source/export.go, internal/source/export_test.go, internal/source/filestorage.go, internal/source/source.go, internal/viewer/handlers.go, internal/viewer/viewer.go, utils/visualise.py
- **async channel info scan**
- **convertor fixes + avatar detection**
- **update chunk visualiser**
=> Chunk optimisations and converter fixes

cmd/slackdump/internal/archive/archive.go, cmd/slackdump/internal/resume/resume.go, cmd/slackdump/main.go, internal/structures/slacktime.go, internal/structures/slacktime_test.go, stream/conversation.go, stream/stream.go
- **fix time parsing**
- **resume logic**
- **disable resume for now**
=> Time parsing fix + "inclusive" stream parameter

internal/viewer/handlers.go
- **fix source detection**
- **test coverage for source detection**
- **add zip files**
- **path check in handler**
=> Add a path check to handlers

cmd/slackdump/internal/man/assets/quickstart.md
=> Update quickstart guide to include tab workaround

internal/chunk/transform/export.go, internal/chunk/transform/export_test.go, internal/source/chunkdir.go, internal/source/dump.go, internal/source/export.go, internal/source/source.go, internal/structures/slacktime.go, internal/viewer/handlers.go, internal/viewer/renderer/slack.go, internal/viewer/renderer/slack_rich_text.go, internal/viewer/renderer/slack_rich_text_test.go, internal/viewer/viewer.go
- **fix transform test**
- **Repoint workspace URLs for supported URLs in viewer.**
- **add getUsers test**
This also relates to #432, at least the links will be pointing to the source message.
=> Update workspace links in viewer to point to local instance

internal/chunk/control/control.go
=> fix DMs not downloading when member-only is requested

internal/network/network.go, internal/network/network_test.go
=> Fix for Unexpected EOF (retry it)

internal/chunk/directory.go
=> skip files starting with "." when reading chunk dir

cmd/slackdump/internal/diag/sdv1/sdv1.go, cmd/slackdump/internal/diag/sdv1/source.go, cmd/slackdump/internal/diag/tools.go, cmd/slackdump/internal/diag/v1.go, internal/convert/src2enc.go, internal/source/chunkdir.go, internal/source/database.go, internal/source/dump.go, internal/source/export.go, internal/source/filestorage.go, internal/source/filestorage_test.go
- **conversion v1->database**
- **implement source v1 and use the converter**
- **cleanup**
- **fix for groups and rename to convertv1**
=> Converter from V1.0.x format

internal/chunk/directory.go
=> fix unhandled walk err

cmd/slackdump/internal/archive/search.go, cmd/slackdump/internal/archive/search_test.go
[Thanks copilot](https://github.com/rusq/slackdump/pull/441#pullrequestreview-2727858294).
=> Mishandled error in search quickfix+test

internal/chunk/chunktest/handlers.go, internal/convert/transform/export.go, internal/fixtures/assets/messages/bot_message.json, internal/fixtures/messages.go, internal/source/chunkdir.go, internal/structures/user_index.go, internal/viewer/handlers.go, internal/viewer/template.go, internal/viewer/template_test.go, internal/viewer/templates/index.html
- **fix bot messages display in viewer**
- **align error handling and fix to-export converter**
=> Fix viewer and 2export converter

cmd/slackdump/internal/format/format.go
=> i483: human friendly format message (v3.1)

internal/viewer/templates/index.html, internal/viewer/templates/styles.html
- **align dms appearance in channel list**
- **reenable thread scrolling**
=> Viewer adjustments

internal/viewer/handlers.go, internal/viewer/templates/index.html
@marcus-crane are you proud of me
(thanks for the UI!)
=> Propagate channel topic to the UI

internal/chunk/directory.go, internal/convert/transform/export.go
=> print filename along with the error

internal/chunk/directory.go, internal/chunk/directory_test.go
=> add a test for invalid json

cmd/slackdump/internal/diag/v1.go, internal/chunk/control/processors.go, internal/convert/convert.go, internal/convert/filecopy.go, internal/convert/src2enc.go, internal/viewer/templates/styles.html, source/doc.go, source/source.go
- converter v1: add ignore on copy error flag
- viewer: enable channel list scroll
- Fixes #504
=> add ignoreCopyErrors and enable channel list scrolling

internal/chunk/backend/dbase/repository/migrations/20250422204803_types.sql
Add types table (enum of all chunk types)
=> Add types table for reference

downloader/downloader.go, source/filestorage.go
=> Sanitise the filename

cmd/slackdump/internal/apiconfig/check.go, cmd/slackdump/internal/apiconfig/new.go, cmd/slackdump/internal/apiconfig/new_test.go, cmd/slackdump/internal/archive/archive.go, cmd/slackdump/internal/archive/search.go, cmd/slackdump/internal/bootstrap/files.go, cmd/slackdump/internal/bootstrap/files_test.go, cmd/slackdump/internal/cfg/cfg.go, cmd/slackdump/internal/convertcmd/convert.go, cmd/slackdump/internal/convertcmd/to_database.go, cmd/slackdump/internal/dump/dump.go, cmd/slackdump/internal/emoji/emoji.go, cmd/slackdump/internal/export/export.go, cmd/slackdump/internal/format/format.go, cmd/slackdump/internal/golang/base/ui.go, cmd/slackdump/internal/golang/base/ui_test.go, cmd/slackdump/internal/list/common.go, cmd/slackdump/internal/resume/resume.go, cmd/slackdump/internal/wizard/wizard.go, cmd/slackdump/internal/workspace/del.go, cmd/slackdump/internal/workspace/new.go, slackdump.1, source/database.go, source/source.go
- **Common AskOverwrite function**
- **ask before overwriting**
- **flags flags review**
Fixes #537
=> Ask before overwriting

cmd/slackdump/internal/workspace/assets/new.md
Re #540.
Document the enteprise login steps.
=> add enterprise steps to workspace new doc

source/filestorage.go
> Grug try Vibe coding once.
> Grug start Claude agent mode. Excitement!
> Agent work hard and long time.
> Plausible looking code, Grug happy. Merge.
> Doesn't work. Users complain.
> Grug kill Copilot with a club. Bad Copilot. Bad code.
> Grug happy.
Roll back vibe-changes made for #522 for standard file storage.
Fixes #554.
=> Rollback changes to standard fs from #522

source/filestorage_test.go
=> Tests for #554
