- slacktime.go
- slacktime_test.go
- url_parse_test.go
* Were modulating with invalid modulator in formatSlackTS. Switch the modulo to modulate modularly.
> Error in parsing thread URL: fix formatSlackTS calculation error

- README.rst
- channels.go
- channels_test.go
- clienter_mock.go
- cmd/slackdump/main.go
- go.mod
- go.sum
- internal/app/app.go
- internal/app/config.go
- messages.go
- options.go
- slackdump.go
- users.go
* progress report on channels and threads
* speed and average speed
* same output style for messages, channels, and threads
* tweak the tier-2 boost
* fetch channels with context to enable ^C termination
* -no-user-cache parameter
> Minor tweaks and UI (ahem) improvements

- clienter_mock.go
- cmd/slackdump/main.go
- slackdump.go
- users.go
- users_test.go
- better wording for invalid_auth error, should it occur.
- there was no error checking when fetching users, hence the invalid_auth was ignored and we failed on len(users) being 0.
> fix error handling in fetchUsers

- channels.go
- channels_test.go
- clienter_mock.go
- options.go
- slackdump.go
- users.go
- users_go118_test.go
- users_test.go
* Slackdump could mistakenly load the users cache from a different  team ID in case it's called consequently for different slack workspaces. 
* Added fuzz tests to filename split/join functions.
> Add Team.ID as a suffix to the user cache filename

- examples/jq/find_matches_print_dates_and_text.sh
- examples/jq/print_messages.sh
This example finds messages that have the word "joined" (case insensitive) in the text attribute.  It converts the epoch timestamps to human readable.  And it outputs the timestamp and the text for each matching message.
> Another jq example

- internal/structures/url_parse.go
- internal/structures/url_parse_test.go
Thanks to @pican79 for flagging this.
Fixes #99:
- updated slack link parsing regexp to allow for dashes in the workspace name.
> Fix URL parsing regexp to allow for spaces

- users.go
- users_test.go
Fixes the OOM error reported in telegram.  Thanks for Al (on telegram) for reporting this and testing on a large environment, as I wouldn't be able to reproduce this locally.
> change the way users are serialised when saving cache

- logger/logger.go
following the quick conversation
introduce logger.Silent in case we want to avoid logging on the terminal while dumping, useful for code using the slackdump API.
HTH.
> new Silent logger PR.

- Makefile
- export/index.go
- internal/fixtures/conversation.go
- internal/fixtures/mpim.go
- internal/structures/mpim.go
- internal/structures/mpim_test.go
- types/users.go
It was reported that some of the mpims do not have names on them.
The problem lied within the way that API return the mpims - sometimes the "members" slice, that normally contains users participating in MPIM, is not populated.
This PR fixes that.
Also, kind of related, a PR is submitted to slack-export-viewer that fixes Internal Server Error in case the export.zip does not contain a directory for mpim listed in mpim.json: https://github.com/hfaran/slack-export-viewer/pull/161
> Fix empty MPIMs shown in slack-export-viewer

- internal/structures/user_index.go
- internal/structures/user_index_test.go
Use real name instead of username, as @mootari linked the article mentioning that usernames will be sunset (article dated 2017)
> change the way user names are displayed in text export

- auth/browser/browser.go
Implements #126
Sets an `OptanonAlertBoxClosed` to a recent time to prevent the cookie banner from appearing.
IT IS ALWAYS A COOKIE TIME
> Set the magic cookie to disable cookie banner for EZ-Login 3000

- README.rst
- doc/usage-export.rst
> Crosslinking to Slackord2

- README.rst
I'm just try to fix snippet examples, and make them more straightforward for new users of the **slackdump** library.
as well as I wanna start seriously contributing on this fancy project.
> fix snippet examples

- export/export.go
- export/export_test.go
- internal/app/emoji/emoji.go
- messages.go
- messages_test.go
- Use name instead of namei\_normalized when naming folders for channels
> #44: fix the different folder name for channels and attachments

- auth/browser/browser.go
While investigating some other issue, and using EZ-Login 3000 with "email login" feature, i started getting strange errors that I've never seen before:
```
2022/10/16 21:21:47 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
```
This did not happen when user/password login type was used.
After successful workspace login with email method (slack sends an email with the code to enter on the login page), slack opens another tab of the [puppet] browser, which quickly sets all advertizing and tracking cookies.
Some facts:
- Total amount of cookies set by slack: 84; out of which
- Cookies with "slack.com" domain and variations: 26
- Tracking and advertising cookies: **58** (!)
The solution is - to cut them off after we grab the cookies from [puppet] browser.
> Ignore thirdparty cookies (set by Slack on browser login)

- README.rst
- doc/usage-export.rst
As per https://github.com/rusq/slackdump/discussions/127#discussioncomment-3925085
> update links to SlackLogViewer

- auth/auth.go
- auth/auth_test.go
- auth/value.go
- internal/app/auth.go
- internal/app/auth_test.go
- Allow auth without cookies (for legacy, bot and app tokens)
> allow auth with legacy/app/bot tokens (without cookies)

- auth/browser/browser.go
Problem: when attempting to login to Slack via Google during EZ-Login 3000 session in the Playwright-taylored Chromium, google denies login attempt with "You're using insecure browser".  Chromium version: 101.0.4929.0.
Switch to Firefox.
Fixes #168
> Switching to Firefox due to inability to login to slack via Google on Chromium

- auth/browser/browser.go
Fixes #168 
Problem: Google auth did not work.
Cause: this is most likely caused by removal of the third-party cookies not matching ".slack.com" domain.
> rollback #158

- cmd/slackdump/interactive.go
> Allow for literal "all" for all channels in export scope selection

- internal/network/network.go
- internal/network/network_test.go
Fixes #186, helps with #172 until it's implemented.
New behaviour:
If Slackdump encounters errors in range [500,599], it initiates the wait.  The wait time for a transient error depends on the current retry attempt number and is calculated as: $(n+2)^3$  seconds, where $n$ is the current attempt, capped at `network.MaxAllowedWaitTime`, which is an exported variable, initially set to 5 minutes, so the wait time for any attempt can't be longer than 5 minutes with the default configuration.
> Retry for 500-599 errors

- channels.go
- channels_test.go
- cmd/slackdump/internal/cfg/cfg.go
- cmd/slackdump/internal/dump/dump.go
- cmd/slackdump/internal/v1/main.go
- cmd/slackdump/internal/workspace/list.go
- cmd/slackdump/main.go
- config.go
- export/expfmt_test.go
- fsadapter/zipfs_test.go
- internal/app/config/config.go
- internal/network/network.go
- internal/network/network_test.go
- logger/logger.go
- logger/logger_test.go
- messages.go
- messages_test.go
- processors.go
- slackdump.go
- slackdump_test.go
- thread.go
- thread_test.go
- users.go
- users_test.go
- remove Logger from slackdump.Config
- reduce wait time for network test
> Refactor logging

- downloader/downloader.go
The "seen" filter was initialised in different goroutines, hence if the same file identical to the one that has already been downloaded (matching file path and file ID) was processed by a different worker, it would still be downloaded.
> fix downloader downloading duplicate files

- channels.go
- internal/network/network.go
- internal/network/network_test.go
- messages.go
- slackdump.go
- thread.go
- users.go
Fixes #234
- introduce retry on net.OpError with exponential backoff
> introduce retry on tcp errors

- internal/app/emoji/emoji.go
Change variable name from `ignoreErrors` to `failFast` (to match `fetch` function) and use this variable instead of always using `true`
> Fix emoji-failfast

- auth/auth.go
- auth/auth_error.go
- auth/browser.go
- auth/browser/client.go
- auth/option.go
It was reported that browser auth fails if the workspace name is not lowercase.
The root cause was it was never able to match the request name when waiting for
features api request, i.e. the browser reported `https://workspace.slack.com/api/...`
and slackdump was expecting `https://WorkSpace.slack.com/api/...`.
> Lowercase the user provided workspace name

- .github/workflows/shellcheck.yml
- .gitignore
- contrib/incremental_backup/dump.sh
- contrib/messages_json_parsing/jq/find_matches_print_dates_and_text.sh
- contrib/messages_json_parsing/jq/print_messages.sh
I (newbie to slackdump) was looking for incremental backup setup. Ran into bash script -- decided to contribute but also to robustify before I "mass try it" since `shellcheck` is right in warning (generally ;-) ) about such constructs as `( $(im_channels) )` since they might not handle correctly cases where names have spaces.  I do not have proof yet though here that it would apply. Neither I have yet tested in this script that the helper `append_to_array` works. 
<details>
<summary>but here is a script which demonstrates problem and checks different solutions for it</summary> 
```shell
#!/bin/bash
function func {
echo word
echo "phrase with space"
echo 'wordwith\n'
}
function func2 {
echo 'last-word\r'
}
function append_to_array {
local array_name="$1"
shift
#local cmd="$@"
if [ -n "$*" …
```
> Add shellcheck CI check + address its concerns in few bash scripts found

- .codespellrc
- .github/workflows/codespell.yml
- cmd/slackdump/main.go
- doc/cli.rst
- downloader/downloader.go
- export/export.go
- export/index.go
- internal/encio/encio_test.go
- internal/network/network_test.go
- internal/structures/entity_list.go
- internal/structures/files/files_test.go
- internal/ui/ask/dump.go
- messages.go
more on codespell: https://github.com/codespell-project/codespell
> Add codespell support: config, github workflow (to detect future typos) + make it fix some typos

- Makefile
- cmd/slackdump/main_test.go
- export/export.go
- export/export_test.go
- internal/app/config/config.go
- internal/app/dump.go
- internal/structures/entity_list.go
- internal/structures/entity_list_test.go
This patch allow to configure `-dump-from` and `-dump-to` limitation per channel.
As channel name you must provide channel ID and dates with format `{CHANNEL_ID}|{OLDEST_TIME}|{LATEST_TIME}`
To dump only specified channel where messages not older
```
slackdump 'C123|2024-04-07T23:02:12' 'C321|2024-01-01T23:02:12'
```
To dump only specified channels where message time between specified time
```
slackdump 'C123|2024-01-07T23:02:12|2024-04-07T23:02:12' 'C321|2024-01-01T23:02:12|2024-03-07T23:02:12'
```
To dump only specified channels where message time  older than specified time
```
slackdump 'C123||2024-04-07T23:02:12' 'C321||2024-03-07T23:02:12'
```
To dump all available channels but channel C123 and C321 only from specified time
```
slackdump '^C123|2024-04-07T23:02:12' …
```
> Add suppor per channel dump-from dump-to limitation

- .github/workflows/release.yml
- .goreleaser.yaml
I did this mostly to include the man page. But this also updates the versions of the actions used in github actions, and uses npmf to create packages.
You can see a sample of the files generated here:
https://github.com/arran4/slackdump/releases/tag/v2.5.8-test4
Also Goreleaser 2 is released https://goreleaser.com/blog/goreleaser-v2/
Thus I got: 
```
/opt/hostedtoolcache/goreleaser-action/2.0.1/x64/goreleaser release --clean
• starting release...
• only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
```
And had to address it.
I am not sure of the purpose of having `ACTIONS_TOKEN` since there is an automatically generated one `GITHUB_TOKEN` (which I needed to use in order to test this.)
```
Subject: [PATCH] 
---
Index: …
```
> Goreleaser improvements

- cmd/slackdump/internal/bootstrap/bootstrap.go
- cmd/slackdump/internal/workspace/workspace.go
- cmd/slackdump/main.go
- internal/cache/manager.go
- internal/cache/manager_test.go
When running slackdump for the first time, i.e.
```
./slackdump archive
```
without prior authentication, it would output the cryptic error message:
```
$ slackdump archive
archive: 2024/07/27 07:24:52 Error 004 (Authentication Error): auth error: workspace does not exist: ""
Error 004 (Authentication Error): auth error: workspace does not exist: ""
exit status 4
```
This PR introduces the change that handles this case correctly, offering to authenticate in a new workspace.
> Offer to authenticate if there are no workspaces

- internal/viewer/templates/styles.html
This PR is a small addition I've made locally while testing out Slack dump that restricts the width of videos.
Mainly just getting my fork ready to do some other changes if/when I get around to them 🙂
**Before**:
**After**:
> (viewer styling): Restrict video width + extend maximum image width

- auth/option.go
- auth/rod.go
- cmd/slackdump/internal/cfg/cfg.go
- cmd/slackdump/internal/workspace/new.go
- go.mod
- go.sum
porting fixes from v2 re #328.
slackauth updated to v0.3.1
2 new flags for auth:
```
-user-agent string
override the user agent string for EZ-Login 3000. It defaults to slackauth.DefaultUserAgent.
-autologin-timeout timeout
headless autologin timeout, without the browser starting time, just the interaction time (default 40s)
```
> user agent and headless timeout

- internal/chunk/file.go
- internal/chunk/file_test.go
- internal/structures/user_index.go
Fixes #324: do not read archived channel users.
> Do not attempt to read channel users for archived channels

- cmd/slackdump/internal/diag/eztest.go
- cmd/slackdump/internal/list/wizard.go
- internal/structures/structures.go
- internal/structures/structures_test.go
- Fix new workspace creation wizard for enterprise instances: failed to correctly parse the workspace name from the API URL.
- list chan/users now generates the correct extension depending on the file type, if the filename is not user-set.
> Fix new workspace creation wizard for enterprise instances + list chan/users fixes

- internal/chunk/dirproc/conversations.go
- internal/chunk/dirproc/conversations_test.go
- stream/conversation.go
- stream/conversation_test.go
Fixes #373: empty message slice passed to message processor may have caused a panic if processor returned an error.
> graceful handling of empty message slices

- Makefile
- auth/browser.go
- auth/browser/browser.go
- auth/option.go
- cmd/slackdump/internal/diag/eztest.go
- cmd/slackdump/internal/diag/record.go
- cmd/slackdump/internal/dump/dump.go
- cmd/slackdump/internal/export/export.go
- cmd/slackdump/internal/export/v2.go
- cmd/slackdump/internal/export/v3.go
- cmd/slackdump/internal/workspace/workspaceui/ezlogin3000.go
- cmd/slackdump/version.go
- export/export.go
- export/export_test.go
- internal/cache/auth.go
- internal/chunk/control/control.go
- internal/chunk/control/interfaces.go
- internal/chunk/control/workers.go
- internal/structures/entity_list.go
- internal/structures/entity_list_test.go
- internal/structures/structures.go
- internal/structures/structures_test.go
- slackdump_test.go
- stream/conversation.go
- stream/stream_test.go
- stream/stream_workers.go
- **allow to specify BUILD_DATE**
- **rename BrowserAuth to PlaywrightAuth**
- **entity list ported + tests**
- **implement #283 in stream**
Fixes #372, also fixes #368.
> Backporting per-channel time-from/time-to (#283)

- cmd/slackdump/internal/archive/assets/archive.md
- cmd/slackdump/internal/archive/assets/search.md
- cmd/slackdump/internal/archive/search.go
- cmd/slackdump/internal/diag/edge.go
- cmd/slackdump/internal/diag/uninstall.go
- cmd/slackdump/internal/diag/wizdebug.go
- cmd/slackdump/internal/emoji/assets/emoji.md
- cmd/slackdump/internal/emoji/emoji.go
- cmd/slackdump/internal/export/assets/export.md
- cmd/slackdump/internal/export/export.go
- cmd/slackdump/internal/man/assets/syntax.md
- cmd/slackdump/internal/man/syntax.go
- cmd/slackdump/internal/view/assets/view.md
- cmd/slackdump/internal/view/view.go
- cmd/slackdump/internal/workspace/assets/del.md
- cmd/slackdump/internal/workspace/assets/import.md
- cmd/slackdump/internal/workspace/assets/list.md
- cmd/slackdump/internal/workspace/assets/new.md
- cmd/slackdump/internal/workspace/del.go
- cmd/slackdump/internal/workspace/new.go
- cmd/slackdump/main.go
- internal/chunk/file.go
- internal/osext/move.go
- internal/structures/entity_list.go
- internal/structures/entity_list_test.go
- internal/viewer/source/filestorage.go
- internal/viewer/source/filestorage_test.go
- **documentation**
- **add more doc**
- **Updating docs**
- **fix for windows paths**
Slackdump view wasn't working properly on Windows.  The problem rooted
in using filepath.Join on a fs.FS.  Even though it was an os.DirFS and
Windows, it expected the Unix path separators.  Fixed by replacing the
filepath.Join with path.Join.
> Documentation and viewer fix on Windows

- cmd/slackdump/internal/apiconfig/apiconfig.go
- cmd/slackdump/internal/apiconfig/check.go
- cmd/slackdump/internal/man/assets/syntax.md
- cmd/slackdump/internal/ui/cfgui/configuration.go
Update the file picker in the Global Config wizard page to search for TOML instead of YAML files.
> global config file picker expected yaml

- cmd/slackdump/internal/diag/redownload.go
- cmd/slackdump/internal/diag/tools.go
- internal/network/network.go
- internal/network/network_test.go
- stream/conversation.go
- utils/count_chunks.sh
Fixes #399.
- when network functions experience EOF it is a recoverable error.
- `slackdump tools redownload` allows to redownload any failed files in the archive, or download all files, if the files download was turned off during the initial run.
> add redownload tool and treat EOF as recoverable error

- clienter_mock_test.go
- internal/chunk/dirproc/conversations.go
- internal/chunk/transform/fileproc/fileproc.go
- internal/edge/wrapper.go
- slackdump.go
- stream/conversation.go
- stream/mock_stream/mock_stream.go
- stream/stream.go
- stream/stream_workers.go
- stream/stream_workers_test.go
- **Channel canvas support**
- **add canvas test**
Canvases are treated as files.  If the canvas is found in
`channel.properties.canvas`, it is passed to file processor.
Slack returns canvases as HTML documents.
Fixes #225
> Add support for channel canvases

- cmd/slackdump/internal/archive/archive.go
- cmd/slackdump/internal/archive/archive_wizard.go
- cmd/slackdump/internal/archive/search.go
- cmd/slackdump/internal/archive/search_wizard.go
- cmd/slackdump/internal/cfg/cfg.go
- cmd/slackdump/internal/dump/dump.go
- cmd/slackdump/internal/export/export.go
- cmd/slackdump/internal/export/v3.go
- cmd/slackdump/internal/export/wizard.go
- cmd/slackdump/internal/ui/cfgui/common_params.go
- internal/chunk/control/control.go
- internal/network/network_test.go
- internal/viewer/source/export_test.go
- Add a -files-rec flag that allows to record file chunks in the archive.  This is generally not required, as the files are retained in the messages within message chunks.  Adding this for completeness.
> add a flag to record file chunks in archives

- cmd/slackdump/internal/view/view.go
- On some machines Chrome was expecting https on localhost.
Fixes #405, only-thread view support will be done separately.
> Change the default listener address for viewer

- cmd/slackdump/internal/man/assets/transfer.md
- cmd/slackdump/internal/man/transfer.go
- cmd/slackdump/main.go
- slackdump.1
> Update documentation to describe machine ID override

- internal/source/source.go
- internal/viewer/renderer/debug.go
- internal/viewer/renderer/renderer.go
- internal/viewer/renderer/slack.go
- internal/viewer/renderer/slack_rich_text.go
- internal/viewer/renderer/slack_rich_text_test.go
- internal/viewer/renderer/slack_test.go
- internal/viewer/template.go
> escape RTSE text

- cmd/slackdump/internal/cfg/cfg_test.go
- cmd/slackdump/internal/cfg/timevalue.go
- cmd/slackdump/internal/cfg/timevalue_test.go
- internal/chunk/dirproc/conversations.go
- internal/chunk/file.go
- internal/network/network.go
- internal/network/network_test.go
- internal/structures/entity_list.go
- internal/structures/entity_list_test.go
- slackdump.1
- stream/conversation.go
- stream/conversation_test.go
- utils/hammer.sh
- Fixes #428 
- Remove the need to type the whole Date Time when only date is specified, i.e. "2019-01-31" vs before one had to specify full date time: "2019-01-31T00:00:00"
- Add tests to stream callback functions (thread, files)
> Fix for API not returning the whole thread, just the parent

- cmd/slackdump/internal/export/v3.go
- internal/chunk/transform/fileproc/sp_export.go
- internal/chunk/transform/fileproc/storagetype.go
Appears it's being used by slack-export-viewer, and maybe other tools, see #436.
> Undeprecate STD storage type

- cmd/slackdump/main.go
In response to #415.
Running as a user in Docker introduces a lot of unnecessary complexity.
> Courageously run as root, but warn.

- auth/auth.go
- auth/auth_ui/huh.go
- auth/browser.go
- auth/rod.go
- cmd/slackdump/internal/diag/info.go
- cmd/slackdump/internal/diag/info/os.go
- cmd/slackdump/internal/format/format.go
- cmd/slackdump/internal/workspace/workspace.go
- cmd/slackdump/internal/workspace/workspaceui/workspaceui.go
- cmd/slackdump/main.go
- internal/osext/osext.go
- internal/osext/terminal.go
- internal/osext/user.go
- tools info:
- wire the -no-encryption and -machine-id flags to `tools info` to be able to test auth (-auth)
- move environment detection to osext and update references
- rod and playwright now refuse to run on dumb terminals
> Dumb terminal detection + add terminal info to diag output

- internal/edge/search.go
Fixes this message during search in verbose mode:
```
DEBUG pagination !BADKEY="signal.NotifyContext(context.Background, [interrupt]).WithValue(trace.traceContextKey, *trace.Task).WithValue(auth.ctxKey,
<...>
```
> fix slog debug args

- cmd/slackdump/internal/emoji/emoji.go
- cmd/slackdump/internal/emoji/emojidl/emoedge.go
- cmd/slackdump/internal/emoji/emojidl/emoji.go
- cmd/slackdump/internal/emoji/emojidl/emoji_test.go
Fixes #452
- Download gifs as gifs, pngs as pngs.
- Output flag was omitted, restored.
> download gifs as gifs

- README.md
Fix a typo in `README.md` where there's an extra colon character.
> Fix typo in README.md: s/::/:/

- internal/viewer/viewer.go
While there's a `/static/` path wired up in the viewer's HTTP server, it defaults to the root of the git repo(?) which is fairly unexpected.
The static folder may be used for #458 to serve eg; avatar placeholders but it's not immediately clear that will be the case.
> Check for static folder relative to viewer module

- .github/workflows/docker.yml
- .github/workflows/go.yml
- .github/workflows/shellcheck.yml
- internal/network/network_test.go
Somehow this slipped through the CI tests - invalid function signature (from the future release) was committed into v3.0.x branch.
Fixes #471.
> Fix the callback function signature in unexpected EOF test

- internal/chunk/control/runner.go
Controller's generator goroutine sync even if the function fails.
> defer wait to ensure it synchronises even if the error happens

- cmd/slackdump/internal/convertcmd/to_dump.go
- cmd/slackdump/internal/dump/dump.go
- cmd/slackdump/internal/format/dump.go
- cmd/slackdump/internal/format/format.go
- cmd/slackdump/internal/format/source.go
- internal/format/csv.go
- internal/format/format.go
- internal/format/json.go
- internal/format/text.go
- internal/nametmpl/template.go
- internal/structures/entity_list.go
- **formatter for any source** - relates to #483 
- **fixes the discrepancy in handling the dump file naming between "dump" and "convert" command** - the drawback is that dump naming templates need to have extension defined in them, i.e. if your template was `{{.ID}}{{ if .ThreadTS}}-{{.ThreadTS}}{{end}}` it should be changed to `{{.ID}}{{ if .ThreadTS}}-{{.ThreadTS}}{{end}}.json`. (This applies only to dump output format)
> Universal formatter (supports any source)

- cmd/slackdump/internal/archive/search.go
- cmd/slackdump/internal/cfg/cfg.go
- cmd/slackdump/internal/convertcmd/convert.go
- cmd/slackdump/internal/diag/record.go
- cmd/slackdump/internal/diag/v1.go
- cmd/slackdump/internal/dump/dump.go
- cmd/slackdump/internal/emoji/emoji.go
- cmd/slackdump/internal/emoji/emojidl/emoedge.go
- cmd/slackdump/internal/emoji/emojidl/emoji.go
- cmd/slackdump/internal/emoji/emojidl/emoji_test.go
- cmd/slackdump/internal/emoji/wizard.go
- cmd/slackdump/internal/export/v3_test.go
- Support for `-files=true|false`
- Enable `-workspace` flag.
Fixes #487.
Future improvements: modification of the edge Emoji download function to adhere to rate limits.
> Add support for -files=true|false to emoji command

- cmd/slackdump/internal/cfg/cfg.go
- cmd/slackdump/internal/list/common.go
- cmd/slackdump/internal/list/wizard.go
- internal/format/csv.go
- internal/format/format.go
- internal/format/text.go
Fixes i491.
- Introduces `-b` flag for `list users` and `list channels` commands, that will enable the
"bare output format".  Only user or channel IDs will be printed, one per line.
> Bare list output format

- go.mod
- go.sum
- internal/chunk/control/workers.go
- stream/conversation.go
- stream/stream.go
- **udpate the slack lib to handle string attachment id**
- **better streaming errors**
Fixes #492
> Cater for string Attachment IDs

- internal/chunk/directory.go
- internal/chunk/file.go
Re: #501.
Treat JSON errors as warning while parsing Channels during view or conversion.
Problematic files will be skipped.
> treat json errors as warnings

- cmd/slackdump/internal/list/common.go
List commands write a file to disk, and with the recent change they were asking
for overwrite confirmation. Flag `-y` wasn't enabled for list commands, and now
it is.
> Quick fix for list commands not having YesMan flag enabled
